Repository gardener/machine-controller-manager, pull requests merged in 2018-05, with the labels that each got.

#84 Bugfix: Fixes bug while deploying machines backed by SSD on GCP
  pkg/apis/machine/validation/gcpmachineclass.go
Labels: bug, gcp

#85 Bugfix: Azure NIC and VM creation made into a transaction
  pkg/driver/driver_azure.go
Labels: azure, bug, ok-to-test

#87 Enabled and integrated unit tests in build.
  .ci/test
  pkg/util/taints/taints_test.go
Labels: ok-to-test

#90 Introduce constants for machine class secret data keys
  pkg/apis/machine/v1alpha1/types.go
  pkg/driver/driver_aws.go
  pkg/driver/driver_azure.go
  pkg/driver/driver_gcp.go
  pkg/driver/driver_openstack.go
Labels: enhancement, ok-to-test

#96 Unit Testcase in machine.go for checking health of the machine
  pkg/controller/machine.go
  pkg/controller/machine_test.go
Labels: kind/enhancement

#97 Issue #78: Update failed machine object state
  pkg/controller/machine.go
Labels: kind/enhancement

#98 Machine health considers - Kubelet and DiskPressure status
  pkg/controller/machine.go
  pkg/controller/machine_test.go
Labels: kind/enhancement
