Repository gardener/machine-controller-manager, pull requests merged in 2018-12, with the labels that each got.

#193 Using default hostname in Alicloud.
  pkg/driver/driver_alicloud.go
  pkg/driver/driver_alicloud_test.go
Labels: needs/ok-to-test

#199 Updated CI test image to support python 3.6
  .ci/pipeline_definitions
Labels: area/operations, kind/test, platform/all, priority/critical, size/xs, status/accepted

#204 indicate proper path to managevm cli
  docs/development/local_setup.md
Labels: area/documentation, component/machine-controller-manager, kind/cleanup, priority/normal, reviewed/lgtm, size/xs, status/accepted
