Repository gardener/machine-controller-manager, pull requests merged in 2018-04, with the labels that each got.

#61 BugFix: Azure now tracks of all VMs resources
  pkg/controller/machine.go
  pkg/controller/machine_safety.go
  pkg/controller/machineset.go
  pkg/driver/driver.go
  pkg/driver/driver_aws.go
  pkg/driver/driver_azure.go
  pkg/driver/driver_fake.go
  pkg/driver/driver_gcp.go
  pkg/driver/driver_openstack.go
Labels: azure, bug

#68 Bugfix: Draining issue and Azure error handling
  pkg/controller/machine.go
  pkg/driver/driver_azure.go
Labels: bug

#77 Fixed linting issue in openstack driver
  pkg/driver/driver_openstack.go
Labels: ok-to-test
