Repository gardener/machine-controller-manager, pull requests merged in 2018-03, with the labels that each got.

#53 Integration of safety controller
  Makefile
  cmd/machine-controller-manager/app/controllermanager.go
  cmd/machine-controller-manager/app/options/options.go
  pkg/apis/machine/types.go
  pkg/apis/machine/v1alpha1/types.go
  pkg/apis/machine/validation/awsmachineclass.go
  pkg/apis/machine/validation/azuremachineclass.go
  pkg/apis/machine/validation/gcpmachineclass.go
  pkg/apis/machine/validation/machine.go
  pkg/apis/machine/validation/machinedeployment.go
  pkg/apis/machine/validation/machineset.go
  pkg/apis/machine/validation/openstackmachineclass.go
  pkg/controller/controller.go
  pkg/controller/deployment.go
  pkg/controller/machine.go
  pkg/controller/machine_safety.go
  pkg/controller/machineset.go
  pkg/driver/driver.go
  pkg/driver/driver_aws.go
  pkg/driver/driver_azure.go
  pkg/driver/driver_fake.go
  pkg/driver/driver_gcp.go
  pkg/driver/driver_openstack.go
  pkg/options/types.go
Labels: enhancement

#56 Added Azure support for safety controller
  docs/design/README.md
  docs/development/new_cp_support.md
  kubernetes/azure-machine-class.yaml
  pkg/apis/machine/validation/azuremachineclass.go
  pkg/controller/machine_safety.go
  pkg/driver/driver_azure.go
Labels: azure, enhancement

#57 Added GCP support for safety controller
  kubernetes/gcp-machine-class.yaml
  pkg/apis/machine/validation/gcpmachineclass.go
  pkg/controller/machine_safety.go
  pkg/driver/driver_aws.go
  pkg/driver/driver_azure.go
  pkg/driver/driver_gcp.go
  pkg/driver/driver_openstack.go
Labels: enhancement, gcp

#58 Set VERSION to 0.2.0-dev
  VERSION
Labels: ok-to-test

#60 Machine prioritization while scale down
  pkg/controller/controller_utils.go
  pkg/controller/machine.go
Labels: enhancement
