Repository gardener/machine-controller-manager, pull requests merged in 2019-08, with the labels that each got.

#300 Split force deletion
  pkg/controller/drain.go
  pkg/controller/drain_test.go
  pkg/controller/machine.go
Labels: needs/ok-to-test

#301 Bugfix: Allows force deletion of pods who have no controllers backing them (#300)
  pkg/controller/drain.go
  pkg/controller/drain_test.go
  pkg/controller/machine.go
Labels: needs/ok-to-test

#302 Regenerated API Types because the latest Version is not checked in
  pkg/apis/machine/v1alpha1/zz_generated.conversion.go
  pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/machine/zz_generated.deepcopy.go
  pkg/client/clientset/internalversion/fake/register.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/informers/externalversions/machine/v1alpha1/alicloudmachineclass.go
  pkg/client/informers/externalversions/machine/v1alpha1/awsmachineclass.go
  pkg/client/informers/externalversions/machine/v1alpha1/azuremachineclass.go
  pkg/client/informers/externalversions/machine/v1alpha1/gcpmachineclass.go
  pkg/client/informers/externalversions/machine/v1alpha1/machine.go
  pkg/client/informers/externalversions/machine/v1alpha1/machinedeployment.go
  pkg/client/informers/externalversions/machine/v1alpha1/machineset.go
  pkg/client/informers/externalversions/machine/v1alpha1/machinetemplate.go
  pkg/client/informers/externalversions/machine/v1alpha1/openstackmachineclass.go
  pkg/client/informers/externalversions/machine/v1alpha1/packetmachineclass.go
  pkg/client/informers/internalversion/machine/internalversion/alicloudmachineclass.go
  pkg/client/informers/internalversion/machine/internalversion/awsmachineclass.go
  pkg/client/informers/internalversion/machine/internalversion/azuremachineclass.go
  pkg/client/informers/internalversion/machine/internalversion/gcpmachineclass.go
  pkg/client/informers/internalversion/machine/internalversion/machine.go
  pkg/client/informers/internalversion/machine/internalversion/machinedeployment.go
  pkg/client/informers/internalversion/machine/internalversion/machineset.go
  pkg/client/informers/internalversion/machine/internalversion/machinetemplate.go
  pkg/client/informers/internalversion/machine/internalversion/openstackmachineclass.go
  pkg/client/informers/internalversion/machine/internalversion/packetmachineclass.go
Labels: needs/ok-to-test

#294 Log NodeTemplate updates
  pkg/controller/deployment_util.go
  pkg/controller/machineset.go
Labels: needs/ok-to-test

#310 Updated local dev setup guide
  docs/development/local_setup.md
Labels: needs/ok-to-test

#309 Improve logs while draining
  pkg/controller/drain.go
Labels: needs/ok-to-test

#303 Removed optional annotation in internal types
  pkg/apis/machine/types.go
Labels: needs/ok-to-test

#316 Deletes nodes object on machine deletion
  pkg/controller/machine.go
  pkg/controller/machine_test.go
Labels: kind/bug, needs/ok-to-test

#311 Added additional OpenStack credentials for DomainID, TenantID, UserDomainName
  go.mod
  go.sum
  kubernetes/Secrets/openstack-secret.yaml
  pkg/apis/machine/v1alpha1/types.go
  pkg/driver/driver_openstack.go
  vendor/github.com/gophercloud/gophercloud/.gitignore
  vendor/github.com/gophercloud/gophercloud/.travis.yml
  vendor/github.com/gophercloud/gophercloud/.zuul.yaml
  vendor/github.com/gophercloud/gophercloud/FAQ.md
  vendor/github.com/gophercloud/gophercloud/MIGRATING.md
  vendor/github.com/gophercloud/gophercloud/README.md
  vendor/github.com/gophercloud/gophercloud/STYLEGUIDE.md
  vendor/github.com/gophercloud/gophercloud/auth_options.go
  vendor/github.com/gophercloud/gophercloud/auth_result.go
  vendor/github.com/gophercloud/gophercloud/doc.go
  vendor/github.com/gophercloud/gophercloud/errors.go
  vendor/github.com/gophercloud/gophercloud/go.mod
  vendor/github.com/gophercloud/gophercloud/go.sum
  vendor/github.com/gophercloud/gophercloud/openstack/auth_env.go
  vendor/github.com/gophercloud/gophercloud/openstack/client.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/keypairs/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/microversions.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/endpoint_location.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tenants/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/utils/base_endpoint.go
  vendor/github.com/gophercloud/gophercloud/pagination/pager.go
  vendor/github.com/gophercloud/gophercloud/params.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/github.com/gophercloud/gophercloud/results.go
  vendor/github.com/gophercloud/gophercloud/service_client.go
  vendor/github.com/gophercloud/utils/LICENSE
  vendor/github.com/gophercloud/utils/openstack/clientconfig/doc.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/results.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/utils.go
  vendor/modules.txt
Labels: needs/ok-to-test

#315 Further improved logs while draining
  pkg/controller/drain.go
Labels: needs/ok-to-test

#313 Bugfix: Eliminates creation of orphan NICs when VM creation fails
  pkg/driver/driver_azure.go
Labels: kind/bug, needs/ok-to-test, platform/az, priority/blocker

#319 Bugfix: Improve the management of finalizers and re-enqueue-mechanism for MachineClasses and Secrets
  pkg/controller/alicloudmachineclass.go
  pkg/controller/awsmachineclass.go
  pkg/controller/azuremachineclass.go
  pkg/controller/gcpmachineclass.go
  pkg/controller/openstackmachineclass.go
  pkg/controller/packetcloudmachineclass.go
  pkg/controller/secret.go
Labels: needs/ok-to-test

#320 Bugfix/delete unhealthy machines
  pkg/controller/drain.go
  pkg/controller/drain_test.go
  pkg/controller/machine.go
  pkg/controller/machine_test.go
  pkg/controller/machineset.go
Labels: needs/ok-to-test, needs/tests

#321 Unit-tests for PR #319
  pkg/controller/secret_test.go
Labels: needs/ok-to-test

#322 Bugfix: Attempt deletion of node only if it isn't blank
  pkg/controller/machine.go
Labels: needs/ok-to-test

#325 Revert "Bugfix: Attempt deletion of node only if it isn't blank"
  pkg/controller/machine.go
Labels: reviewed/ok-to-test

#324 Bugfix: Delete node only if nodeName isn't empty
  pkg/controller/machine.go
Labels: needs/ok-to-test

#323 Rel-0.21.1-dev: Delete node only if nodeName isn't empty
  pkg/controller/machine.go
Labels: needs/ok-to-test

#327 Few negative unit-tests for the feature supporting taints, annotations and labels
  pkg/controller/machine_util_test.go
Labels: needs/ok-to-test

#328 Added missing user_domain_id secret field
  kubernetes/Secrets/openstack-secret.yaml
  pkg/apis/machine/v1alpha1/types.go
  pkg/driver/driver_openstack.go
Labels: needs/ok-to-test
