Repository gardener/machine-controller-manager, pull requests merged in 2019-09, with the labels that each got.

#329 makes MCM GCP driver to differentiate user-data from startup-script
  pkg/driver/driver_gcp.go
Labels: needs/ok-to-test

#326 Add URN field in AzureMachineClass
  kubernetes/machine_classes/azure-machine-class.yaml
  pkg/apis/machine/types.go
  pkg/apis/machine/v1alpha1/types.go
  pkg/apis/machine/v1alpha1/zz_generated.conversion.go
  pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/machine/validation/azuremachineclass.go
  pkg/apis/machine/zz_generated.deepcopy.go
  pkg/driver/driver_azure.go
  pkg/openapi/openapi_generated.go
Labels: needs/ok-to-test

#331 Use tzdata package instead of zoneinfo.zip
  Dockerfile
  assets/zoneinfo.zip
Labels: plaltform/alicloud, status/accepted, topology/seed

#335 Add support for zoned Azure machines
  kubernetes/machine_classes/azure-machine-class.yaml
  pkg/apis/machine/types.go
  pkg/apis/machine/v1alpha1/types.go
  pkg/apis/machine/v1alpha1/zz_generated.conversion.go
  pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/machine/validation/azuremachineclass.go
  pkg/apis/machine/zz_generated.deepcopy.go
  pkg/driver/driver_azure.go
  pkg/openapi/openapi_generated.go
Labels: needs/ok-to-test, reviewed/ok-to-test

#336 More frequent freeze checker during integration tests
  .ci/integration-tests
Labels: kind/test, needs/ok-to-test
