Repository gardener/machine-controller-manager, pull requests merged in 2019-03, with the labels that each got.

#233 Fixed empty machineID issue and enhanced print statements
  pkg/controller/machine.go
  pkg/controller/machine_safety.go
  pkg/driver/cmi-client.go
Labels: area/dev-productivity, component/machine-controller-manager, exp/beginner, kind/cleanup, needs/review, platform/all, priority/normal, size/xs, status/new, topology/seed

#236 Bugfix: AliCloud now generates the right provider-ID
  pkg/driver/driver_alicloud.go
Labels: area/operations, kind/bug, needs/ok-to-test

#239 Bugfix: MachineSet unfreeze now goes through
  pkg/controller/machine_safety.go
Labels: area/operations, kind/bug, needs/review, priority/blocker, size/s, status/in-delivery, topology/seed

#244 Fix make check
  .ci/check
Labels: component/machine-controller-manager, exp/beginner, kind/regression, needs/ok-to-test, priority/critical, size/xs, status/accepted, topology/seed

#241 Unit tests for machineset controller
  pkg/controller/controller_suite_test.go
  pkg/controller/controller_utils.go
  pkg/controller/machineset.go
  pkg/controller/machineset_test.go
Labels: component/machine-controller-manager, kind/test, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m, status/accepted, topology/seed
