Repository gardener/machine-controller-manager, pull requests merged in 2019-12, with the labels that each got.

#362 Prefix tags with 'v'
  VERSION
Labels: needs/ok-to-test

#364 Allow deletion of machine without status.currentStatus.phase
  pkg/controller/machineset.go
Labels: kind/bug, needs/ok-to-test

#366 Add csi volume fetching for AliCloud
  pkg/driver/driver_alicloud.go
Labels: needs/ok-to-test

#365 Bugfix: Remove dependency on MachineClass while deleting MachineDeployment/MachineSets
  pkg/controller/deployment.go
  pkg/controller/machineset.go
Labels: kind/bug, needs/ok-to-test

#370 Increase MaxEvictRetries and PodEvictionRetryInterval
  pkg/controller/drain.go
  pkg/controller/drain_test.go
  pkg/controller/machine.go
Labels: needs/ok-to-test

#374 Added support for OpenStack image id
  go.mod
  go.sum
  kubernetes/machine_classes/openstack-machine-class.yaml
  pkg/apis/machine/types.go
  pkg/apis/machine/v1alpha1/types.go
  pkg/apis/machine/v1alpha1/zz_generated.conversion.go
  pkg/apis/machine/validation/openstackmachineclass.go
  pkg/driver/driver_openstack.go
  pkg/openapi/openapi_generated.go
Labels: needs/ok-to-test

#375 Activate healthz earlier
  cmd/machine-controller-manager/app/controllermanager.go
  pkg/controller/controller.go
Labels: area/robustness, component/machine-controller-manager, kind/enhancement, needs/ok-to-test, platform/all, priority/normal, size/xs, topology/seed

#373 Avoid force-deleting if previous drain has failed
  pkg/controller/drain.go
  pkg/controller/machine.go
  pkg/controller/machine_test.go
Labels: needs/ok-to-test
