Repository gardener/machine-controller-manager, pull requests merged in 2020-01, with the labels that each got.

#351 Add bootstrap token generation
  go.mod
  go.sum
  pkg/controller/machine.go
  pkg/controller/machine_bootstrap_token.go
  pkg/driver/driver.go
  pkg/driver/driver_alicloud.go
  pkg/driver/driver_aws.go
  pkg/driver/driver_azure.go
  pkg/driver/driver_fake.go
  pkg/driver/driver_gcp.go
  pkg/driver/driver_openstack.go
  pkg/driver/driver_packet.go
  vendor/k8s.io/cluster-bootstrap/LICENSE
  vendor/k8s.io/cluster-bootstrap/token/api/doc.go
  vendor/k8s.io/cluster-bootstrap/token/api/types.go
  vendor/k8s.io/cluster-bootstrap/token/util/helpers.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/modules.txt
Labels: do-not-merge/work-in-progress, needs/ok-to-test

#378 Support multiple Disks/Security Groups on AWS
  pkg/apis/machine/validation/awsmachineclass.go
  pkg/apis/machine/validation/awsmachineclass_test.go
  pkg/controller/drain.go
  pkg/controller/drain_test.go
  pkg/driver/driver_aws.go
  pkg/driver/driver_aws_test.go
Labels: kind/enhancement, needs/ok-to-test, platform/aws

#384 added MachineClass for incremental out-of-tree migration
  pkg/apis/machine/register.go
  pkg/apis/machine/types.go
  pkg/apis/machine/v1alpha1/register.go
  pkg/apis/machine/v1alpha1/types.go
  pkg/apis/machine/v1alpha1/zz_generated.conversion.go
  pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/machine/zz_generated.deepcopy.go
  pkg/client/clientset/internalversion/typed/machine/internalversion/fake/fake_machine_client.go
  pkg/client/clientset/internalversion/typed/machine/internalversion/fake/fake_machineclass.go
  pkg/client/clientset/internalversion/typed/machine/internalversion/generated_expansion.go
  pkg/client/clientset/internalversion/typed/machine/internalversion/machine_client.go
  pkg/client/clientset/internalversion/typed/machine/internalversion/machineclass.go
  pkg/client/clientset/versioned/typed/machine/v1alpha1/fake/fake_machine_client.go
  pkg/client/clientset/versioned/typed/machine/v1alpha1/fake/fake_machineclass.go
  pkg/client/clientset/versioned/typed/machine/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/machine/v1alpha1/machine_client.go
  pkg/client/clientset/versioned/typed/machine/v1alpha1/machineclass.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/machine/v1alpha1/interface.go
  pkg/client/informers/externalversions/machine/v1alpha1/machineclass.go
  pkg/client/informers/internalversion/generic.go
  pkg/client/informers/internalversion/machine/internalversion/interface.go
  pkg/client/informers/internalversion/machine/internalversion/machineclass.go
  pkg/client/listers/machine/internalversion/expansion_generated.go
  pkg/client/listers/machine/internalversion/machineclass.go
  pkg/client/listers/machine/v1alpha1/expansion_generated.go
  pkg/client/listers/machine/v1alpha1/machineclass.go
  pkg/openapi/openapi_generated.go
Labels: needs/ok-to-test

#388 Added Cinder based Custom Root Disks for OpenStack Vms
  kubernetes/machine_classes/openstack-machine-class.yaml
  pkg/apis/machine/types.go
  pkg/apis/machine/v1alpha1/types.go
  pkg/apis/machine/v1alpha1/zz_generated.conversion.go
  pkg/apis/machine/validation/openstackmachineclass.go
  pkg/driver/driver_openstack.go
  pkg/openapi/openapi_generated.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/urls.go
  vendor/modules.txt
Labels: needs/ok-to-test

#387 Update status when replicas undefined or equal to zero
  pkg/apis/machine/v1alpha1/types.go
  pkg/openapi/openapi_generated.go
Labels: needs/ok-to-test

#391 Bugfix: Fixes race between machine & machineSet creation/deletion operations
  cmd/machine-controller-manager-cli/main.go
  pkg/controller/machine.go
  pkg/controller/machine_safety.go
  pkg/controller/machine_test.go
  pkg/driver/driver.go
  pkg/driver/driver_alicloud.go
  pkg/driver/driver_aws.go
  pkg/driver/driver_azure.go
  pkg/driver/driver_fake.go
  pkg/driver/driver_gcp.go
  pkg/driver/driver_openstack.go
  pkg/driver/driver_packet.go
  pkg/fakeclient/client.go
Labels: kind/bug, needs/ok-to-test

#395 Azure: Allow to manage machine with identity
  kubernetes/machine_classes/azure-machine-class.yaml
  pkg/apis/machine/types.go
  pkg/apis/machine/v1alpha1/types.go
  pkg/apis/machine/v1alpha1/zz_generated.conversion.go
  pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/machine/zz_generated.deepcopy.go
  pkg/client/clientset/internalversion/typed/machine/internalversion/fake/fake_machineclass.go
  pkg/client/clientset/internalversion/typed/machine/internalversion/machineclass.go
  pkg/client/clientset/versioned/typed/machine/v1alpha1/fake/fake_machineclass.go
  pkg/client/clientset/versioned/typed/machine/v1alpha1/machineclass.go
  pkg/client/informers/externalversions/machine/v1alpha1/machineclass.go
  pkg/client/informers/internalversion/machine/internalversion/machineclass.go
  pkg/client/listers/machine/internalversion/machineclass.go
  pkg/client/listers/machine/v1alpha1/machineclass.go
  pkg/driver/driver_azure.go
  pkg/openapi/openapi_generated.go
Labels: needs/ok-to-test

#399 Bugfix: Fixed regressions from PR-379
  pkg/driver/driver_aws.go
Labels: needs/ok-to-test
