Repository gardener/machine-controller-manager, pull requests merged in 2020-11, with the labels that each got.

#548 OOT: Fixes drain timeout issues on retires
  pkg/util/provider/machinecontroller/machine.go
  pkg/util/provider/machinecontroller/machine_util.go
Labels: kind/regression, needs/ok-to-test, reviewed/lgtm, size/s

#545 Deploy VMs into existing OpenStack Neutron network
  kubernetes/crds/machine.sapcloud.io_openstackmachineclasses.yaml
  pkg/apis/machine/types.go
  pkg/apis/machine/v1alpha1/openstack_machineclass_types.go
  pkg/apis/machine/v1alpha1/zz_generated.conversion.go
  pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/machine/zz_generated.deepcopy.go
  pkg/driver/driver_openstack.go
  pkg/openapi/openapi_generated.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/urls.go
  vendor/modules.txt
Labels: kind/api-change, needs/changes, needs/ok-to-test, size/m

#551 Fix the OpenAPI validation of the machine-deployment crd
  docs/development/cp_support_new.md
  kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#554 Fixed regression (OOT) with maxEvictRetries and defaulted drain timeout to 2hours
  pkg/controller/drain.go
  pkg/util/provider/drain/drain.go
  pkg/util/provider/machinecontroller/controller_suite_test.go
  pkg/util/provider/machinecontroller/machine_util.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#550 Adapt integration tests to handle possibly orphaned resources
  .ci/integration-tests
Labels: needs/ok-to-test, size/m

#558 Use listers to get the machine-object during reconciliation
  pkg/controller/machine.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#557 OOT: Introduce backoff in re-enqueuing machines during creation/deletion failures
  pkg/controller/machine.go
  pkg/util/provider/machinecontroller/controller_suite_test.go
  pkg/util/provider/machinecontroller/machine.go
  pkg/util/provider/machinecontroller/machine_safety.go
  pkg/util/provider/machinecontroller/machine_test.go
  pkg/util/provider/machinecontroller/machine_util.go
  pkg/util/provider/machinecontroller/machine_util_test.go
  pkg/util/provider/machinecontroller/migrate_machineclass.go
  pkg/util/provider/machinecontroller/migrate_machineclass_test.go
  pkg/util/provider/machineutils/utils.go
  pkg/util/strings/string.go
Labels: kind/regression, needs/ok-to-test, needs/second-opinion, size/xl

#559 Allow migration to continue when machineClass with same name as Provi…
  pkg/util/provider/machinecontroller/migrate_machineclass.go
  pkg/util/provider/machinecontroller/migrate_machineclass_test.go
Labels: needs/ok-to-test, priority/blocker, size/m

#564 Set Machine Phase to Terminating & make drain calculations based on deletionTimestamp
  pkg/controller/controller_suite_test.go
  pkg/controller/machine.go
  pkg/util/provider/machinecontroller/controller_suite_test.go
  pkg/util/provider/machinecontroller/machine_test.go
  pkg/util/provider/machinecontroller/machine_util.go
  pkg/util/time/time.go
  pkg/util/time/time_suite_test.go
  pkg/util/time/time_test.go
Labels: kind/regression, needs/ok-to-test, needs/second-opinion, size/l

#569 Prepare Next Dev Cycle v0.35.1-dev
  VERSION
Labels: needs/review, reviewed/ok-to-test, size/xs

#571 Cherrypick PR#564 to v0.35
  pkg/controller/controller_suite_test.go
  pkg/controller/machine.go
  pkg/util/provider/machinecontroller/controller_suite_test.go
  pkg/util/provider/machinecontroller/machine_test.go
  pkg/util/provider/machinecontroller/machine_util.go
  pkg/util/time/time.go
  pkg/util/time/time_suite_test.go
  pkg/util/time/time_test.go
Labels: needs/ok-to-test, reviewed/lgtm, size/l

#572 Cherrypick PR#564 to v0.34
  Dockerfile
  pkg/controller/controller_suite_test.go
  pkg/controller/machine.go
  pkg/util/provider/machinecontroller/controller_suite_test.go
  pkg/util/provider/machinecontroller/machine_test.go
  pkg/util/provider/machinecontroller/machine_util.go
  pkg/util/time/time.go
  pkg/util/time/time_suite_test.go
  pkg/util/time/time_test.go
Labels: needs/ok-to-test, needs/second-opinion, size/l

#573 Update docker images to use latest gcr copy
  Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#574 Update docker images to use gcr copy
  Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#568 Add FAQ for paused field
  docs/FAQ.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#566 Fix Azure machine deletion if resource group is gone
  pkg/driver/driver_azure.go
Labels: needs/changes, needs/ok-to-test, reviewed/lgtm, size/xs

#575 Prevent panic when machine template hash length is < 5
  pkg/controller/deployment_sync.go
Labels: kind/bug, kind/regression, needs/ok-to-test, reviewed/lgtm, size/xs

#577 Cherrypick PR#575 into MCM rel-v0.35
  pkg/controller/deployment_sync.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
