Repository gardener/machine-controller-manager, pull requests merged in 2020-12, with the labels that each got.

#578 Support optional secret containing only credentials but no user-data; accept Gardener secret data keys
  cmd/machine-controller-manager-cli/main.go
  kubernetes/Secrets/alicloud-secret.yaml
  kubernetes/Secrets/aws-secret.yaml
  kubernetes/Secrets/azure-secret.yaml
  kubernetes/Secrets/gcp-secret.yaml
  kubernetes/crds/machine.sapcloud.io_alicloudmachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_awsmachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_azuremachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_gcpmachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_machineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml
  kubernetes/crds/machine.sapcloud.io_openstackmachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_packetmachineclasses.yaml
  kubernetes/machine_classes/alicloud-machine-class.yaml
  kubernetes/machine_classes/aws-machine-class.yaml
  kubernetes/machine_classes/azure-machine-class.yaml
  kubernetes/machine_classes/gcp-machine-class.yaml
  kubernetes/machine_classes/openstack-machine-class.yaml
  kubernetes/machine_classes/packet-machine-class.yaml
  pkg/apis/machine/types.go
  pkg/apis/machine/v1alpha1/alicoud_machineclass_types.go
  pkg/apis/machine/v1alpha1/aws_machineclass_types.go
  pkg/apis/machine/v1alpha1/azure_machineclass_types.go
  pkg/apis/machine/v1alpha1/gcp_machineclass_types.go
  pkg/apis/machine/v1alpha1/machineclass_types.go
  pkg/apis/machine/v1alpha1/openstack_machineclass_types.go
  pkg/apis/machine/v1alpha1/packet_machineclass_types.go
  pkg/apis/machine/v1alpha1/zz_generated.conversion.go
  pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/machine/zz_generated.deepcopy.go
  pkg/controller/machine.go
  pkg/controller/machine_safety.go
  pkg/controller/machine_test.go
  pkg/controller/machine_util.go
  pkg/controller/secret.go
  pkg/controller/secret_util.go
  pkg/driver/driver.go
  pkg/driver/driver_alicloud.go
  pkg/driver/driver_aws.go
  pkg/driver/driver_aws_test.go
  pkg/driver/driver_azure.go
  pkg/driver/driver_gcp.go
  pkg/driver/driver_openstack.go
  pkg/driver/driver_packet.go
  pkg/driver/driver_suite_test.go
  pkg/driver/driver_test.go
  pkg/openapi/openapi_generated.go
  pkg/util/provider/machinecontroller/machine.go
  pkg/util/provider/machinecontroller/machine_safety.go
  pkg/util/provider/machinecontroller/machine_test.go
  pkg/util/provider/machinecontroller/machine_util.go
  pkg/util/provider/machinecontroller/migrate_machineclass.go
  pkg/util/provider/machinecontroller/secret.go
  pkg/util/provider/machinecontroller/secret_util.go
Labels: area/open-source, area/usability, kind/api-change, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xl

#581 Migration note for OOT providers
  README.md
Labels: needs/ok-to-test, needs/review, reviewed/ok-to-test, size/xs

#582 Update pull_request_template.md
  .github/pull_request_template.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
