Repository gardener/machine-controller-manager, pull requests merged in 2020-07, with the labels that each got.

#457 [openstack] Config drive option
  kubernetes/crds/machine.sapcloud.io_openstackmachineclasses.yaml
  pkg/apis/machine/types.go
  pkg/apis/machine/v1alpha1/openstack_machineclass_types.go
  pkg/apis/machine/v1alpha1/zz_generated.conversion.go
  pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/machine/zz_generated.deepcopy.go
  pkg/driver/driver_openstack.go
  pkg/openapi/openapi_generated.go
Labels: needs/ok-to-test, reviewed/lgtm

#478 Enable controller configurations via MachineDeployment
  cmd/machine-controller-manager/app/options/options.go
  kubernetes/machine_objects/machine-deployment.yaml
  pkg/apis/machine/types.go
  pkg/apis/machine/v1alpha1/machine_types.go
  pkg/apis/machine/v1alpha1/shared_types.go
  pkg/apis/machine/v1alpha1/zz_generated.conversion.go
  pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/machine/zz_generated.deepcopy.go
  pkg/controller/deployment_sync.go
  pkg/controller/deployment_util.go
  pkg/controller/machine.go
  pkg/controller/machineset.go
  pkg/controller/machineset_util.go
  pkg/openapi/openapi_generated.go
  pkg/util/provider/machinecontroller/machine_util.go
Labels: kind/test, needs/ok-to-test, reviewed/lgtm

#487 Bugfix/finalizers
  pkg/util/provider/machinecontroller/controller.go
  pkg/util/provider/machinecontroller/controller_suite_test.go
  pkg/util/provider/machinecontroller/machine.go
  pkg/util/provider/machinecontroller/machine_util.go
  pkg/util/provider/machinecontroller/machineclass.go
  pkg/util/provider/machinecontroller/secret.go
  pkg/util/provider/machinecontroller/secret_test.go
Labels: kind/bug, needs/ok-to-test, priority/critical, reviewed/lgtm

#491 Increased concurrent worker syncs from 5 --> 10
  cmd/machine-controller-manager/app/options/options.go
  pkg/util/provider/app/options/options.go
Labels: needs/ok-to-test

#489 Use channel id for posting slack release notes
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm
