Repository gardener/machine-controller-manager, pull requests merged in 2020-09, with the labels that each got.

#496 Inhibit scale-down by autoscaler during roll-outs.
  cmd/machine-controller-manager/app/controllermanager.go
  cmd/machine-controller-manager/app/options/options.go
  pkg/controller/controller.go
  pkg/controller/controller_utils.go
  pkg/controller/controller_utils_test.go
  pkg/controller/deployment_recreate.go
  pkg/controller/deployment_rolling.go
  pkg/controller/deployment_rolling_test.go
  pkg/controller/deployment_util.go
  pkg/options/types.go
  pkg/util/annotations/annotations.go
  pkg/util/annotations/annotations_suite_test.go
  pkg/util/annotations/annotations_test.go
  pkg/util/taints/taints.go
Labels: needs/ok-to-test, reviewed/lgtm

#505 Changes missed out by PR #492
  pkg/controller/controller_utils.go
  pkg/controller/deployment_rollback.go
  pkg/controller/deployment_rolling.go
  pkg/controller/machine_util.go
  pkg/util/conditions/conditions.go
  pkg/util/nodeops/conditions.go
  pkg/util/nodeops/taints.go
  pkg/util/provider/machinecontroller/machine_test.go
  pkg/util/provider/machinecontroller/machine_util.go
  pkg/util/provider/machineutils/utils.go
Labels: kind/regression, needs/ok-to-test, priority/critical, reviewed/lgtm

#509 Wait also for CSI PVs during serial eviction
  pkg/driver/driver_alicloud.go
  pkg/driver/driver_aws.go
  pkg/driver/driver_aws_test.go
  pkg/driver/driver_azure.go
  pkg/driver/driver_azure_test.go
  pkg/driver/driver_gcp.go
  pkg/driver/driver_gcp_test.go
  pkg/driver/driver_openstack.go
  pkg/driver/driver_openstack_test.go
  pkg/util/provider/machinecontroller/controller.go
  pkg/util/provider/machinecontroller/machine_test.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm

#511 ServerGroup option for Openstack MachineClass
  kubernetes/crds/machine.sapcloud.io_openstackmachineclasses.yaml
  kubernetes/machine_classes/openstack-machine-class.yaml
  pkg/apis/machine/types.go
  pkg/apis/machine/v1alpha1/openstack_machineclass_types.go
  pkg/apis/machine/v1alpha1/zz_generated.conversion.go
  pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/machine/zz_generated.deepcopy.go
  pkg/driver/driver_openstack.go
  pkg/openapi/openapi_generated.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/schedulerhints/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/schedulerhints/requests.go
  vendor/modules.txt
Labels: needs/ok-to-test, reviewed/lgtm

#516 AWS: Allow deletion of VMs even on list image or modify instance failure
  pkg/driver/driver_aws.go
Labels: needs/ok-to-test, reviewed/lgtm

#518 AWS: Allow deletion of VMs even on get images / modify instance failures.
  pkg/driver/driver_aws.go
Labels: needs/ok-to-test, reviewed/lgtm

#520 Allow deletion of VM even on image/instance get failures.
  pkg/driver/driver_aws.go
Labels: needs/ok-to-test, reviewed/lgtm

#507 [azure] Verify tags
  pkg/driver/driver_azure.go
Labels: needs/ok-to-test, reviewed/lgtm

#521 [OOT] Re-enabled support for bootstrap token injection
  pkg/util/provider/machinecontroller/controller.go
  pkg/util/provider/machinecontroller/machine.go
  pkg/util/provider/machinecontroller/machine_test.go
Labels: kind/regression, needs/ok-to-test
