Repository gardener/machine-controller-manager, pull requests merged in 2021-08, with the labels that each got.

#637 It suite improvements
  kubernetes/crds/machine.sapcloud.io_alicloudmachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_awsmachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_azuremachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_gcpmachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_machineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml
  kubernetes/crds/machine.sapcloud.io_machines.yaml
  kubernetes/crds/machine.sapcloud.io_machinesets.yaml
  kubernetes/crds/machine.sapcloud.io_openstackmachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_packetmachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_scales.yaml
  pkg/test/integration/common/framework.go
Labels: merge/squash, needs/ok-to-test, reviewed/lgtm, size/s

#640 using controller-gen latest version for crd generation
  Makefile
  kubernetes/crds/machine.sapcloud.io_alicloudmachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_awsmachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_azuremachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_gcpmachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_machineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml
  kubernetes/crds/machine.sapcloud.io_machines.yaml
  kubernetes/crds/machine.sapcloud.io_machinesets.yaml
  kubernetes/crds/machine.sapcloud.io_openstackmachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_packetmachineclasses.yaml
  pkg/openapi/openapi_generated.go
Labels: size/xl, reviewed/lgtm

#641 Fix CRD manifests
  kubernetes/crds/machine.sapcloud.io_machineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml
  kubernetes/crds/machine.sapcloud.io_machines.yaml
  kubernetes/crds/machine.sapcloud.io_machinesets.yaml
  pkg/apis/machine/v1alpha1/machine_types.go
  pkg/apis/machine/v1alpha1/machineclass_types.go
  pkg/apis/machine/v1alpha1/shared_types.go
  pkg/openapi/openapi_generated.go
Labels: needs/review, needs/ok-to-test, size/s

#643 Updates scales crd to v1
  kubernetes/crds/machine.sapcloud.io_scales.yaml
Labels: needs/ok-to-test, size/m, reviewed/lgtm, kind/regression
