Repository gardener/machine-controller-manager, pull requests merged in 2021-07, with the labels that each got.

#614 fix to propagate the error on to the dashboard
  pkg/util/provider/machinecontroller/machine_util.go
Labels: lifecycle/rotten, needs/ok-to-test, reviewed/lgtm, size/xs

#628 Clarify when to apply the force deletion label
  docs/FAQ.md
Labels: needs/ok-to-test, size/xs

#629 Increasing concurrent object syncs to 50
  pkg/util/provider/app/options/options.go
Labels: needs/ok-to-test, needs/review, size/xs

#632 Update go version on pipeline
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
