Repository gardener/machine-controller-manager, pull requests merged in 2021-01, with the labels that each got.

#585 Correcting the variable substitution
  pkg/controller/machine.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#587 docforge manifest
  .docforge/manifest.yaml
Labels: area/documentation, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#589 Avoid the deletion of the machines in CrashLoopBackoff state by the safety controller
  pkg/controller/machine_safety.go
  pkg/controller/machine_safety_test.go
  pkg/controller/machine_test.go
  pkg/driver/driver.go
  pkg/driver/driver_fake.go
  pkg/util/provider/driver/fake.go
  pkg/util/provider/machinecontroller/machine_safety.go
  pkg/util/provider/machinecontroller/machine_safety_test.go
  pkg/util/provider/machinecontroller/machine_test.go
  pkg/util/provider/machinecontroller/machineclass_test.go
  pkg/util/provider/machinecontroller/migrate_machineclass_test.go
Labels: needs/ok-to-test, reviewed/lgtm, size/l

#591 Check for misconfigured PDBs on Node drain and set proper error description
  kubernetes/deployment/out-of-tree/target-cluster-role.yaml
  pkg/util/provider/app/app.go
  pkg/util/provider/drain/drain.go
  pkg/util/provider/machinecontroller/controller.go
  pkg/util/provider/machinecontroller/machine_util.go
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s
