Repository gardener/machine-controller-manager, pull requests merged in 2021-05, with the labels that each got.

#605 Skip node drain on readOnlyFileSystem condition
  pkg/util/provider/machinecontroller/machine_test.go
  pkg/util/provider/machinecontroller/machine_util.go
Labels: reviewed/lgtm, size/l

#607 Improved log details to include node name and provider ID
  pkg/util/provider/machinecontroller/machine.go
  pkg/util/provider/machinecontroller/machine_safety.go
  pkg/util/provider/machinecontroller/machine_util.go
Labels: reviewed/lgtm, size/s

#609 Fix panic when secretRef cannot be found
  pkg/controller/machine_util.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#611 Adds finalizers on machines that are adopted by the machine controller
  .gitignore
  pkg/util/provider/machinecontroller/machine.go
  pkg/util/provider/machinecontroller/machine_test.go
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#615 updated the ci pipeline image
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/xs
