Repository gardener/machine-controller-manager, pull requests merged in 2022-05, with the labels that each got.

#712 update local_setup.sh
  Makefile
  hack/local_setup.sh
Labels: size/xs, reviewed/lgtm

#713 Alpine and golang image updated
  .ci/pipeline_definitions
  Dockerfile
Labels: size/xs, needs/ok-to-test, reviewed/lgtm

#710 Updated content structure
  .docforge/manifest.yaml
  docs/documents/apis.md
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#723 Fixed broken links - 05.2022
  docs/FAQ.md
Labels: size/xs, needs/ok-to-test, reviewed/lgtm

#700 Added docs/todo/outline.md
  docs/todo/outline.md
Labels: needs/ok-to-test, size/m, reviewed/lgtm
