Repository gardener/machine-controller-manager, pull requests merged in 2022-01, with the labels that each got.

#662 Switch leader election to endpointleases
  kubernetes/deployment/in-tree/control-cluster-role.yaml
  kubernetes/deployment/out-of-tree/control-cluster-role.yaml
  pkg/util/client/leaderelectionconfig/config.go
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#668 Retry with Backoff for machineset finalizer update
  pkg/controller/machineset.go
  pkg/controller/machineset_test.go
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#667 Trigger orphan collection on OutOfRange machine status
  pkg/util/provider/machinecontroller/controller.go
  pkg/util/provider/machinecontroller/machine_safety.go
  pkg/util/provider/machinecontroller/machine_safety_test.go
Labels: needs/ok-to-test, size/m, reviewed/lgtm

#672 Fixed broken links 01.2022
  docs/FAQ.md
  docs/development/cp_support_new.md
  docs/development/integration_tests.md
  docs/proposals/external_providers_grpc.md
Labels: size/xs, needs/ok-to-test, reviewed/lgtm

#676 Log Node conditions when Machine is considered as unhealthy
  pkg/controller/machine.go
  pkg/util/provider/machinecontroller/machine_util.go
Labels: kind/enhancement, area/ops-productivity, size/xs, needs/ok-to-test, reviewed/lgtm

#677 Node Name column while printing machine objects
  kubernetes/crds/machine.sapcloud.io_machines.yaml
  pkg/apis/machine/v1alpha1/machine_types.go
Labels: size/xs, needs/ok-to-test, reviewed/lgtm

#670 Remove PreserveUnknown field of CredenetialSecretRef
  kubernetes/crds/machine.sapcloud.io_machineclasses.yaml
  pkg/apis/machine/v1alpha1/machineclass_types.go
Labels: size/xs, needs/ok-to-test, reviewed/lgtm
