Repository gardener/machine-controller-manager, pull requests merged in 2022-04, with the labels that each got.

#695 FAQ updated related to garbage collection
  docs/FAQ.md
Labels: size/xs, needs/ok-to-test, reviewed/lgtm

#691 Adds permit testing testcases
  pkg/util/permits/permits.go
  pkg/util/permits/permits_test.go
Labels: needs/ok-to-test, size/m, reviewed/lgtm

#697 Refactor ClusterAutoscaler annotations to a separate package
  pkg/controller/autoscaler/types.go
  pkg/controller/deployment_recreate.go
  pkg/controller/deployment_rolling.go
  pkg/controller/deployment_rolling_test.go
  pkg/controller/deployment_util.go
  pkg/util/provider/machinecontroller/machine_util.go
  pkg/util/provider/machinecontroller/machine_util_test.go
Labels: needs/ok-to-test, size/m, reviewed/lgtm

#698 Nit: Fix typos
  docs/development/machine_error_codes.md
  pkg/util/provider/drain/drain.go
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#702 Automated cherry pick of #697: Refactor ClusterAutoscaler annotations to a separate package
  pkg/controller/autoscaler/types.go
  pkg/controller/deployment_recreate.go
  pkg/controller/deployment_rolling.go
  pkg/controller/deployment_rolling_test.go
  pkg/controller/deployment_util.go
  pkg/util/provider/machinecontroller/machine_util.go
  pkg/util/provider/machinecontroller/machine_util_test.go
Labels: needs/ok-to-test, size/m, reviewed/lgtm

#707 Update stale node check to check if node names are equal
  pkg/util/provider/machinecontroller/machine.go
Labels: needs/ok-to-test

#705 Annotate mcm during Integration Tests
  pkg/test/integration/common/framework.go
Labels: size/xs, needs/ok-to-test, reviewed/lgtm

#709 [rel-v0.44] Automated cherry pick of #707: Update stale node check to check if node names are equal
  pkg/util/provider/machinecontroller/machine.go
Labels: needs/ok-to-test

#689 Update manifest.yaml
  .docforge/manifest.yaml
Labels: size/xs, needs/ok-to-test, reviewed/lgtm
