Repository gardener/machine-controller-manager, pull requests merged in 2022-09, with the labels that each got.

#744 Handle `PodDisruptionBudget` `policy/v1`
  go.mod
  go.sum
  pkg/util/k8sutils/version.go
  pkg/util/provider/app/app.go
  pkg/util/provider/drain/drain.go
  pkg/util/provider/drain/drain_test.go
  pkg/util/provider/machinecontroller/controller.go
  pkg/util/provider/machinecontroller/machine_util.go
  vendor/github.com/Masterminds/semver/.travis.yml
  vendor/github.com/Masterminds/semver/CHANGELOG.md
  vendor/github.com/Masterminds/semver/LICENSE.txt
  vendor/github.com/Masterminds/semver/Makefile
  vendor/github.com/Masterminds/semver/README.md
  vendor/github.com/Masterminds/semver/appveyor.yml
  vendor/github.com/Masterminds/semver/collection.go
  vendor/github.com/Masterminds/semver/constraints.go
  vendor/github.com/Masterminds/semver/doc.go
  vendor/github.com/Masterminds/semver/version.go
  vendor/github.com/Masterminds/semver/version_fuzz.go
  vendor/modules.txt
Labels: needs/ok-to-test, reviewed/lgtm, size/l, merge/squash

#743 Support URL encoded bootstrap token replacement
  pkg/controller/machine_bootstrap_token.go
  pkg/util/provider/machinecontroller/machine_bootstrap_token.go
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#746 Add nodeName and providerID column while listing machines(s)
  Makefile
  docs/documents/apis.md
  kubernetes/crds/machine.sapcloud.io_alicloudmachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_awsmachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_azuremachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_gcpmachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_machineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml
  kubernetes/crds/machine.sapcloud.io_machines.yaml
  kubernetes/crds/machine.sapcloud.io_machinesets.yaml
  kubernetes/crds/machine.sapcloud.io_openstackmachineclasses.yaml
  kubernetes/crds/machine.sapcloud.io_packetmachineclasses.yaml
  pkg/apis/machine/v1alpha1/machine_types.go
Labels: needs/ok-to-test, size/m, reviewed/lgtm
