Repository gardener/machine-controller-manager, pull requests merged in 2022-07, with the labels that each got.

#732 Build Multi-Arch Images 📦
  .ci/build
  .ci/pipeline_definitions
  Dockerfile
  Makefile
Labels: kind/enhancement, area/delivery, needs/ok-to-test, reviewed/lgtm, size/s

#733 Mark machine failed during rollout also
  pkg/controller/controller_suite_test.go
  pkg/util/provider/machinecontroller/machine_util.go
  pkg/util/provider/machinecontroller/machine_util_test.go
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#735 Fixed broken links
  README.md
  docs/documents/apis.md
Labels: size/xs, needs/ok-to-test, reviewed/lgtm

#736 Removed flaky test case
  pkg/controller/deployment_test.go
Labels: size/xs, needs/ok-to-test, reviewed/lgtm

#711 Migrate leader election to leases
  kubernetes/deployment/in-tree/control-cluster-role.yaml
  kubernetes/deployment/in-tree/target-cluster-role.yaml
  kubernetes/deployment/out-of-tree/control-cluster-role.yaml
  kubernetes/deployment/out-of-tree/target-cluster-role.yaml
  pkg/util/client/leaderelectionconfig/config.go
Labels: kind/enhancement, size/xs, needs/ok-to-test, reviewed/lgtm
