Repository gardener/machine-controller-manager, pull requests merged in 2023-12, with the labels that each got.

#878 switch GCR -> Artifact-Registry
  .ci/pipeline_definitions
  Makefile
  kubernetes/deployment/out-of-tree/deployment.yaml
Labels: reviewed/ok-to-test, size/xs, needs/ok-to-test, reviewed/lgtm

#868 Proposal: Post Create Initialization
  docs/proposals/initialize-machine-triggercreationflow.mmd
  docs/proposals/initialize-machine-triggercreationflow.svg
  docs/proposals/initialize-machine.md
Labels: reviewed/ok-to-test, needs/ok-to-test, size/m, reviewed/lgtm

#879 Fixed MCM restart during cleanup
  pkg/test/integration/common/framework.go
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#877 Reduce noisy reconciles + enhance logs
  cmd/machine-controller-manager/app/controllermanager.go
  docs/documents/apis.md
  kubernetes/crds/machine.sapcloud.io_machines.yaml
  pkg/apis/machine/v1alpha1/machine_types.go
  pkg/util/provider/app/app.go
  pkg/util/provider/drain/drain.go
  pkg/util/provider/drain/volume_attachment.go
  pkg/util/provider/machinecontroller/controller.go
  pkg/util/provider/machinecontroller/machine.go
  pkg/util/provider/machinecontroller/machine_safety.go
  pkg/util/provider/machinecontroller/machine_test.go
  pkg/util/provider/machinecontroller/machine_util.go
  pkg/util/provider/machinecontroller/machine_util_test.go
  pkg/util/provider/machinecontroller/machineclass.go
  pkg/util/provider/machinecontroller/machineclass_util.go
  pkg/util/provider/machinecontroller/secret.go
  pkg/util/provider/machineutils/utils.go
Labels: reviewed/ok-to-test, size/xl, needs/ok-to-test, reviewed/lgtm

#882 Support checking GKE version schema
  pkg/util/k8sutils/version.go
Labels: size/xs, needs/ok-to-test, reviewed/lgtm

#884 Env var for IT tests
  docs/development/integration_tests.md
  pkg/test/integration/common/framework.go
Labels: size/xs, needs/ok-to-test, reviewed/lgtm, merge/squash

#887 Check, update node label on machine obj prior to drain,termination
  pkg/util/provider/machinecontroller/machine_util.go
Labels: reviewed/ok-to-test, needs/ok-to-test, reviewed/lgtm, size/s

#886 Some updates to FAQ
  docs/FAQ.md
  docs/images/machine_phase_transition.png
Labels: reviewed/ok-to-test, needs/review, size/xs, needs/ok-to-test
