Repository gardener/machine-controller-manager, pull requests merged in 2023-06, with the labels that each got.

#821 Keep `DesiredReplicas` annotation up to date even if no scaling happens
  pkg/controller/deployment_sync.go
  pkg/controller/deployment_sync_test.go
Labels: size/xs, needs/ok-to-test, reviewed/lgtm

#824 Automated cherry pick of #821: keep desired replicas annotation up to date even if no
  pkg/controller/deployment_sync.go
  pkg/controller/deployment_sync_test.go
Labels: needs/review, size/xs, needs/ok-to-test

#822 Automated cherry pick of #821: keep desired replicas annotation up to date even if no
  pkg/controller/deployment_sync.go
  pkg/controller/deployment_sync_test.go
Labels: size/xs, needs/ok-to-test, reviewed/lgtm

#823 Refactor metrics code
  kubernetes/deployment/out-of-tree/deployment.yaml
  pkg/controller/metrics.go
  pkg/metrics/metrics.go
  pkg/util/provider/machinecontroller/metrics.go
  pkg/util/provider/metrics/metrics.go
Labels: reviewed/ok-to-test, size/xl, needs/ok-to-test, reviewed/lgtm

#819 Updated/added entries to FAQ
  docs/FAQ.md
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#808 Add metric to track Unhealthy Stale machine removal count
  pkg/controller/machineset.go
  pkg/controller/machineset_test.go
  pkg/controller/metrics.go
  pkg/metrics/metrics.go
  pkg/util/provider/machinecontroller/machine.go
  pkg/util/provider/metrics/metrics.go
Labels: kind/enhancement, reviewed/ok-to-test, needs/ok-to-test, size/m, area/monitoring, reviewed/lgtm

#827 Upgrade golang version to v1.20.5
  .ci/pipeline_definitions
  Dockerfile
  go.mod
  vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go
  vendor/modules.txt
Labels: reviewed/ok-to-test, size/xs

#830 Updated the docforge manifest & added index files
  .docforge/manifest.yaml
  README.md
  docs/README.md
  docs/deployment/_index.md
  docs/deployment/kubernetes.md
  docs/development/_index.md
  docs/development/local_setup.md
  docs/documents/_index.md
  docs/proposals/_index.md
  docs/todo/_index.md
  docs/usage/_index.md
Labels: needs/review, needs/ok-to-test, size/m

#833 Include `UnavailableReplicas` in MCD status update check
  pkg/controller/deployment_util.go
Labels: needs/review, size/xs, needs/ok-to-test

#834 [rel-v0.49] Automated cherry pick of #833: include unavailable replicas in mcd status update check
  pkg/controller/deployment_util.go
Labels: kind/bug, needs/review, size/xs, needs/ok-to-test
