Repository gardener/machine-controller-manager, pull requests merged in 2024-01, with the labels that each got.

#847 Introduce the use of central manifest
  .docforge/manifest.yaml
Labels: kind/enhancement, needs/ok-to-test, area/documentation, reviewed/lgtm, size/s

#893 nil fix in MC.updateNodeToMachine
  pkg/util/provider/machinecontroller/machine.go
Labels: size/xs, needs/ok-to-test, reviewed/lgtm

#894 Added `Architecture` in NodeTemplate
  docs/documents/apis.md
  kubernetes/crds/machine.sapcloud.io_machineclasses.yaml
  pkg/apis/machine/types.go
  pkg/apis/machine/v1alpha1/machineclass_types.go
  pkg/apis/machine/v1alpha1/zz_generated.conversion.go
  pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/machine/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
Labels: reviewed/ok-to-test, kind/api-change, needs/ok-to-test, size/m, reviewed/lgtm
