Repository gardener/machine-controller-manager, pull requests merged in 2024-06, with the labels that each got.

#916 chore: Update Concourse URL
  README.md
Labels: needs/review, size/xs, needs/ok-to-test, area/documentation, reviewed/lgtm, kind/cleanup

#917 Update `github.com/Masterminds/semver` to v3
  go.mod
  go.sum
  pkg/util/k8sutils/version.go
  pkg/util/provider/app/app.go
  pkg/util/provider/drain/drain.go
  pkg/util/provider/machinecontroller/controller.go
Labels: size/xs, needs/ok-to-test, reviewed/lgtm

#922 Fix docker image
  Makefile
Labels: reviewed/ok-to-test, size/xs, needs/ok-to-test, reviewed/lgtm
