Repository gardener/machine-controller-manager, pull requests merged in 2024-07, with the labels that each got.

#920 Improved context with timeout for DrainNode
  pkg/util/provider/drain/drain.go
Labels: reviewed/ok-to-test, size/xs, needs/ok-to-test, reviewed/lgtm

#927 Fix API doc
  docs/documents/apis.md
  hack/api-reference/providerspec-config.json
  hack/api-reference/template/members.tpl
  hack/api-reference/template/type.tpl
  pkg/client/informers/externalversions/factory.go
  pkg/openapi/openapi_generated.go
Labels: reviewed/ok-to-test, size/xl, needs/ok-to-test, reviewed/lgtm

#928 Allow deletion to proceed in case of VM initialization error
  .gitignore
  Makefile
  hack/gardener_local_setup.sh
  pkg/util/provider/machinecontroller/machine_util.go
Labels: size/xs, needs/ok-to-test, reviewed/lgtm

#931 [Cherry-pick rel-v0.53] Allow deletion to proceed in case of VM initialization error (#928)
  .gitignore
  Makefile
  hack/gardener_local_setup.sh
  pkg/util/provider/machinecontroller/machine_util.go
Labels: reviewed/ok-to-test, size/xs, needs/ok-to-test, reviewed/lgtm

#932 Add namespace to dummy machine object so that driver can rely on the namespace being set
  pkg/util/provider/machinecontroller/machine_safety.go
Labels: reviewed/ok-to-test, size/xs, needs/ok-to-test, reviewed/lgtm
