Repository gardener/machine-controller-manager, pull requests merged in 2024-04, with the labels that each got.

#898 VM Instance Initialization: Driver.InitializeMachine
  docs/development/cp_support_new.md
  docs/development/machine_error_codes.md
  pkg/util/provider/driver/driver.go
  pkg/util/provider/driver/fake.go
  pkg/util/provider/machinecodes/codes/code_string.go
  pkg/util/provider/machinecodes/codes/codes.go
  pkg/util/provider/machinecontroller/machine.go
  pkg/util/provider/machinecontroller/machine_test.go
  pkg/util/provider/machineutils/utils.go
Labels: reviewed/ok-to-test, needs/ok-to-test, size/m, reviewed/lgtm

#906 Diagnostics Logs for MCM
  cmd/machine-controller-manager/app/controllermanager.go
  pkg/controller/controller_utils.go
  pkg/controller/deployment_rolling.go
  pkg/controller/deployment_sync.go
  pkg/controller/deployment_util.go
  pkg/controller/machineset.go
  pkg/controller/machineset_util.go
  pkg/util/provider/machinecontroller/machine_util.go
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#899 Enhanced local IT setup
  docs/development/integration_tests.md
  hack/gardener_local_setup.sh
  hack/non_gardener_local_setup.sh
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#915 disable CICD Pipelines for stale branch
  .ci/pipeline_definitions
Labels: area/delivery, needs/ok-to-test, reviewed/lgtm, kind/cleanup, size/s

#914 disable CICD Pipelines for stale branch
  .ci/pipeline_definitions
Labels: area/delivery, needs/ok-to-test, reviewed/lgtm, kind/cleanup, size/s

#913 disable CICD Pipelines for stale branch
  .ci/pipeline_definitions
Labels: area/delivery, needs/ok-to-test, reviewed/lgtm, kind/cleanup, size/s

#912 disable CICD Pipelines for stale branch
  .ci/pipeline_definitions
Labels: area/delivery, needs/ok-to-test, reviewed/lgtm, kind/cleanup, size/s

#911 disable CICD Pipelines for stale branch
  .ci/pipeline_definitions
Labels: area/delivery, needs/ok-to-test, reviewed/lgtm, kind/cleanup, size/s

#910 disable CICD Pipelines for stale branch
  .ci/pipeline_definitions
Labels: area/delivery, needs/ok-to-test, reviewed/lgtm, kind/cleanup, size/s

#909 disable CICD Pipelines for stale branch
  .ci/pipeline_definitions
Labels: area/delivery, needs/ok-to-test, reviewed/lgtm, kind/cleanup, size/s

#908 disable CICD Pipelines for stale branch
  .ci/pipeline_definitions
Labels: area/delivery, needs/ok-to-test, reviewed/lgtm, kind/cleanup, size/s
