Repository gardener/machine-controller-manager, pull requests merged in 2025-07, with the labels that each got.

#1013 run make generate
  docs/documents/apis.md
  kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml
  kubernetes/crds/machine.sapcloud.io_machines.yaml
  kubernetes/crds/machine.sapcloud.io_machinesets.yaml
  pkg/openapi/openapi_generated.go
Labels: needs/review, size/xs, needs/ok-to-test

#1017 Add taint for critical components not ready after update
  pkg/controller/deployment_inplace.go
  pkg/util/provider/machinecontroller/controller.go
  pkg/util/provider/machinecontroller/machine_util.go
Labels: reviewed/ok-to-test, size/xs, needs/ok-to-test, needs/cherry-pick

#1018 [rel-v0.59] Add taint for critical components not ready after update (#1017)
  pkg/controller/deployment_inplace.go
  pkg/util/provider/machinecontroller/controller.go
  pkg/util/provider/machinecontroller/machine_util.go
Labels: reviewed/ok-to-test, size/xs, needs/ok-to-test, reviewed/lgtm

#1016 Updating cnudie labels
  .ci/pipeline_definitions
Labels: size/xs, needs/ok-to-test, reviewed/lgtm

#1015 Fix checking of `MachineCreationTimeout` when machine is `Pending`
  pkg/util/provider/machinecontroller/machine_util.go
  pkg/util/provider/machinecontroller/machine_util_test.go
Labels: reviewed/ok-to-test, needs/ok-to-test, reviewed/lgtm, size/s
