Repository gardener/machine-controller-manager, pull requests merged in 2025-06, with the labels that each got.

#999 fix: use `strconv.ParseBool` for `force-deletion` label
  pkg/util/provider/machinecontroller/machine_util.go
Labels: needs/review, size/xs, needs/ok-to-test

#1000 Add `node_name` label to the `mcm_machine_info` metric
  pkg/util/provider/machinecontroller/metrics.go
  pkg/util/provider/metrics/metrics.go
Labels: needs/review, size/xs, needs/ok-to-test

#1003 Simplify local development
  Dockerfile
  Makefile
Labels: kind/enhancement, reviewed/ok-to-test, size/xs, needs/ok-to-test, reviewed/lgtm

#1006 Add validation for flags passed to machine controller
  cmd/machine-controller-manager/app/options/options.go
  pkg/util/provider/app/options/options.go
Labels: needs/changes, needs/review, needs/ok-to-test, size/s
