Repository gardener/machine-controller-manager, pull requests merged in 2025-08, with the labels that each got.

#1022 export testresults as inlined ocm-resource
  .github/workflows/build.yaml
Labels: reviewed/ok-to-test, size/xs, reviewed/lgtm

#1025 Fix `mcm_machine_set_failed_machines` metric to more accurately reflect current state
  pkg/controller/deployment_machineset_util.go
  pkg/controller/metrics.go
Labels: reviewed/ok-to-test, needs/review, size/xs

#1024 Added VirtualCapacity field to MachineClass NodeTemplate
  docs/documents/apis.md
  kubernetes/crds/machine.sapcloud.io_machineclasses.yaml
  pkg/apis/machine/types.go
  pkg/apis/machine/v1alpha1/machineclass_types.go
  pkg/apis/machine/v1alpha1/zz_generated.conversion.go
  pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/machine/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/util/provider/machinecontroller/machine.go
  pkg/util/provider/machinecontroller/machine_util.go
  pkg/util/provider/machinecontroller/machine_util_test.go
  pkg/util/provider/machinecontroller/machineclass.go
  pkg/util/provider/machineutils/utils.go
Labels: reviewed/ok-to-test, kind/api-change, reviewed/lgtm, size/l

#1029 Log rollout events
  pkg/controller/deployment_inplace.go
  pkg/controller/deployment_recreate.go
  pkg/controller/deployment_rolling.go
Labels: reviewed/ok-to-test, size/xs, reviewed/lgtm
